### ISSUE TITLE
[提案]服务器列表排列顺序

### ISSUE THREAD

**Issue by XBC-D2O** [redstone-skin/server-list#8]
建议：
能否使服务器列表按照在线人数和稳定性排序

**Comment by hempflower** [comment]
服务器可能通过 mod、插件或其他手段修改玩家在线信息，这导致玩家在线信息不可靠。

**Comment by hempflower** [comment]
我在 7d6de821f58bdddf27f3d0df986a92af3b74e193 添加了随机排序，每个服务器机会均等

**Comment by XBC-D2O** [comment]
或者不展示离线服务器？
优先展示红石皮肤站登录的服务器?

**Comment by miaomiaotail** [comment]
随机就蛮好

**Comment by lc6464** [comment]
随机比较好吧。
